# export POSTGRES_USERNAME=POSTGRES_USERNAME
# export POSTGRES_PASSWORD=POSTGRES_PASSWORD
# export POSTGRES_HOST=POSTGRES_HOST
# export POSTGRES_DB=POSTGRES_DB
# export POSTGRES_PORT=POSTGRES_PORT
# export AWS_REGION=AWS_REGION
# export AWS_PROFILE=default
# export AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
# export BCRYPT_PASSWORD=BCRYPT_PASSWORD
# export JWT_SECRET=JWT_SECRET
# export URL=URL
# export PORT=PORT
# export AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
# export SALT_ROUNDS=SALT_ROUNDS

eb setenv POSTGRES_USERNAME POSTGRES_PASSWORD POSTGRES_HOST POSTGRES_DB POSTGRES_PORT AWS_SECRET_ACCESS_KEY BCRYPT_PASSWORD JWT_SECRET URL PORT SALT_ROUNDS